# Generated by Django 2.2.15 on 2020-08-03 20:25

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('ID', models.CharField(default=core.models.create_alpha_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('cuerpo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Actividad')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Origen'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tipo'),
        ),
    ]
